"""
LaTeX tables T1 to T6 (booktabs, ACM acmart compatible, one file each) from analysis/out/paper_v2.1/numbers.csv
(written by paper_stats.py). Read-only on data; every printed number is a numbers.csv row (ids in the
comment line of each file) or a constant from the environment snapshot (T1).

Output: <paper dir>/tables/t1_setup.tex ... t6_thesis_vs_v2.tex, t3b_latency_stream_pipeline.tex (appendix)
Usage:  venv/bin/python analysis/scripts/paper_tables.py [--paper-dir DIR]
"""

import argparse
import csv
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
IN = os.path.join(ROOT, "analysis", "out", "paper_v2.1")
EPS = [("inference", "inf", "2.878"), ("stream", "str", "2.7804"), ("pipeline", "pip", "2.7615")]
CFGS = [("flask", "Flask"), ("django", "Django"), ("flask17w", "Flask 17w"), ("django17w", "Django 17w"),
        ("fastapi", "FastAPI"), ("tornado", "Tornado")]
CS = [1, 5, 10, 25, 50, 100]


def read(path):
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


class N:
    def __init__(self):
        self.n = {r["id"]: r for r in read(os.path.join(IN, "numbers.csv"))}
        self.used = []

    def v(self, i):
        self.used.append(i)
        return float(self.n[i]["value"])

    def ci(self, i):
        self.used.append(i)
        r = self.n[i]
        return (float(r["ci_low"]), float(r["ci_high"])) if r["ci_low"] else (None, None)

    def has(self, i):
        return i in self.n

    def rel(self, i):
        v, (lo, hi) = self.v(i), self.ci(i)
        return None if lo is None else (hi - lo) / 2 / abs(v)


def f(x, nd):
    return f"{x:,.{nd}f}"


def fx(x):
    """throughput: 3 decimals below 10 req/s, 2 above."""
    return f(x, 3) if x < 10 else f(x, 2)


def fci(n, i, nd, pct=False):
    v = n.v(i)
    lo, hi = n.ci(i)
    sgn = "+" if pct and v > 0 else ""
    s = f"{sgn}{f(v, nd)}"
    if lo is not None:
        s += f" [{f(lo, nd)}, {f(hi, nd)}]"
    return s


def write(dirn, name, body, ids):
    text = body.strip() + "\n"
    assert "\u2014" not in text and "\u2013" not in text
    head = (f"% {name}: generated by venv/bin/python analysis/scripts/paper_tables.py from "
            f"analysis/out/paper_v2.1/numbers.csv\n% numbers.csv ids: {compact(ids)}\n")
    with open(os.path.join(dirn, name), "w", encoding="utf-8") as fh:
        fh.write(head + text)


def compact(ids):
    ids = list(dict.fromkeys(ids))
    pre = sorted({i.split(".")[0] for i in ids})
    return f"{len(ids)} ids with prefixes " + ", ".join(pre) if len(ids) > 12 else ", ".join(ids)


def t1(n, d):
    ids = [f"M.S.{e[1]}" for e in EPS] + ["M.first_chunk", "M.chunk_gap", "M.chunks", "M.retrieval", "M.runs_sim",
                                          "M.runs_real", "M.clock_min", "M.clock_max"]
    for i in ids:
        n.v(i)
    body = r"""
\begin{table}
  \caption{Experimental setup. S is the calibrated service time of the upstream call; c is the number of
  closed-loop users. Software versions from the environment snapshot of 28 Sep 2026; one pip-freeze hash in all runs.}
  \label{tab:setup}
  \footnotesize
  \begin{tabular}{@{}p{0.22\columnwidth}p{0.74\columnwidth}@{}}
    \toprule
    Item & Setting \\
    \midrule
    Host & Laptop, Intel Core i5-12500H; WSL2 VM (Linux 6.6.87.2) with 8 vCPUs, 7,942 MiB RAM; clock source tsc, time sync off \\
    Software & Python 3.12.3; Locust 2.43.4 (gevent 25.9.1); psutil 7.2.2; Anthropic SDK 0.88.0 (httpx 0.28.1), one client per process \\
    Sync servers & Flask 3.1.3 and Django 6.0.3 on Gunicorn 25.3.0 sync workers: 1 worker, or 17 workers ($2 \times 8 + 1$) \\
    Async servers & FastAPI 0.135.3 (Starlette 1.0.0) on Uvicorn 0.42.0 (asyncio, h11), 1 process; Tornado 6.5.5, 1 process \\
    Endpoints & inference: one Messages call; stream: server-sent events, one event per upstream chunk; pipeline: parse, retrieval (%(ret)s ms sleep), Messages call, format \\
    Upstream & Deterministic simulator of the Messages API calibrated on real runs (claude-haiku-4-5, 256 output tokens, temperature 0): $S$ = %(si)s s (inference), %(ss)s s (stream: first chunk %(fc)s ms, then %(nc)s chunks %(cg)s ms apart), %(sp)s s (pipeline) \\
    Load & Closed loop, zero think time; $c$ = 1, 5, 10, 25, 50, 100 users; first requests paced over one $S$; 60 s per run; 3 warm-up requests; server restarted for every run \\
    Runs & 5 per cell: %(rs)s simulated runs (4 frameworks $\times$ 3 endpoints $\times$ 6 levels, plus 2 frameworks with 17 workers); %(rr)s real-API runs (3 per level) \\
    Measurement & Per-request log (perf\_counter); windows on the monotonic clock; RSS, USS and CPU of the server process tree every 250 ms; guest/host clock rate %(cmin)s to %(cmax)s \\
    \bottomrule
  \end{tabular}
\end{table}
""" % dict(si=f(n.v("M.S.inf"), 3), ss=f(n.v("M.S.str"), 4), sp=f(n.v("M.S.pip"), 4), fc=f(n.v("M.first_chunk"), 1),
           nc=f(n.v("M.chunks"), 0), cg=f(n.v("M.chunk_gap"), 1), ret=f(n.v("M.retrieval"), 0),
           rs=f(n.v("M.runs_sim"), 0), rr=f(n.v("M.runs_real"), 0), cmin=f(n.v("M.clock_min"), 5),
           cmax=f(n.v("M.clock_max"), 5))
    write(d, "t1_setup.tex", body, ids)


def t2(n, d):
    ids, rows = [], []
    for ep, ea, s in EPS:
        rows.append(rf"    \multicolumn{{7}}{{@{{}}l}}{{\emph{{{ep}}} ($S$ = {s} s)}} \\")
        for ca, lab in CFGS:
            cells = []
            for c in CS:
                x, sh = f"X.{ea}.{ca}.c{c}", f"SH.{ea}.{ca}.c{c}"
                ids += [x, sh]
                cells.append(f"{fx(n.v(x))} ({n.v(sh):.3f})")
            rows.append(f"    {lab} & " + " & ".join(cells) + r" \\")
        rows.append(r"    \addlinespace")
    rows.pop()
    rel = max(n.rel(i) for i in ids if i.startswith("X."))
    body = r"""
\begin{table*}
  \caption{Throughput (req/s, median of 5 runs) and, in parentheses, its share of the theoretical ceiling:
  $1/S$ for one sync worker, $\min(c,17)/S$ for 17 workers, $c/S$ for async. One-worker and 17-worker cells at
  $c \le 17$ use the completion rate in the steady window; 17-worker cells at $c \ge 25$ use the cycle estimator
  (whole service periods of the phase-locked workers). The half-width of the range of the 5 runs (a 93.75\,\%%
  confidence interval for the median) is at most %(rel)s\,\%% of the value in every cell.}
  \label{tab:throughput}
  \footnotesize
  \begin{tabular}{@{}lrrrrrr@{}}
    \toprule
    Configuration & $c=1$ & $c=5$ & $c=10$ & $c=25$ & $c=50$ & $c=100$ \\
    \midrule
%(rows)s
    \bottomrule
  \end{tabular}
\end{table*}
""" % dict(rows="\n".join(rows), rel=f"{rel * 100:.2f}")
    write(d, "t2_throughput.tex", body, ids)


def lat_rows(n, ea, ids):
    rows, rels = [], []
    for ca, lab in CFGS:
        for k, (nm, st) in enumerate((("LM", "mean"), ("L50", "p50"), ("L95", "p95"))):
            cells = []
            for c in CS:
                base = f"{ea}.{ca}.c{c}"
                one = ca in ("flask", "django")
                cens = one and c >= 25
                steady = (one and c in (5, 10)) or (ca.endswith("17w") and c > 17)
                if cens:
                    if nm == "LM":
                        i = f"LR.{base}"
                        ids.append(i)
                        cells.append(rf"\textit{{{f(n.v(i), 0)}}}$^\dagger$")
                    else:
                        cells.append("cens.")
                    continue
                i = f"{nm}.{base}"
                ids.append(i)
                r = n.rel(i)
                rels.append(r)
                cells.append(f"{f(n.v(i), 0)}" + ("$^*$" if steady else ""))
            first = lab if k == 0 else ""
            rows.append(f"    {first} & {st} & " + " & ".join(cells) + r" \\")
        rows.append(r"    \addlinespace")
    rows.pop()
    return rows, max(rels)


LAT_CAPTION = r"""Latency (ms). $^*$ steady state: requests that started after the first queue cycle
  $t_0 + \lceil c/w \rceil S$ ($w$ = 1 or 17 workers), statistics pooled over the 5 runs. $^\dagger$ censored cell
  (one sync worker, $c \ge 25$): no request started after the first queue cycle completes inside the 60 s
  window, so the response-time law $R = N/X = c/X$ is shown (italic) and the measured percentiles (cens.) are
  not reported. Other cells: median over 5 runs of the per-run statistic over all requests (no queue forms).
  Interval half-widths (range of 5 runs; 95\,\%% bootstrap CI over whole runs for $^*$ cells) are at most %(rel)s\,\%% of
  the value in every printed cell."""


def t3(n, d):
    ids = []
    rows, rel = lat_rows(n, "inf", ids)
    body = r"""
\begin{table*}
  \caption{%(cap)s Inference endpoint ($S$ = 2.878 s); stream and pipeline in Table~\ref{tab:latency-app}.}
  \label{tab:latency}
  \footnotesize
  \begin{tabular}{@{}llrrrrrr@{}}
    \toprule
    Configuration & Stat. & $c=1$ & $c=5$ & $c=10$ & $c=25$ & $c=50$ & $c=100$ \\
    \midrule
%(rows)s
    \bottomrule
  \end{tabular}
\end{table*}
""" % dict(cap=LAT_CAPTION % dict(rel=f"{rel * 100:.2f}"), rows="\n".join(rows))
    write(d, "t3_latency.tex", body, ids)
    ids = []
    blocks, rels = [], []
    for ep, ea, s in EPS[1:]:
        rows, rel = lat_rows(n, ea, ids)
        rels.append(rel)
        blocks.append(rf"    \multicolumn{{8}}{{@{{}}l}}{{\emph{{{ep}}} ($S$ = {s} s)}} \\" + "\n" + "\n".join(rows))
    body = r"""
\begin{table*}
  \caption{%(cap)s Stream and pipeline endpoints (appendix).}
  \label{tab:latency-app}
  \footnotesize
  \begin{tabular}{@{}llrrrrrr@{}}
    \toprule
    Configuration & Stat. & $c=1$ & $c=5$ & $c=10$ & $c=25$ & $c=50$ & $c=100$ \\
    \midrule
%(rows)s
    \bottomrule
  \end{tabular}
\end{table*}
""" % dict(cap=LAT_CAPTION % dict(rel=f"{max(rels) * 100:.2f}"), rows="\n    \\midrule\n".join(blocks))
    write(d, "t3b_latency_stream_pipeline.tex", body, ids)


def t4(n, d):
    ids, rows, wide = [], [], 0
    for ep, ea, s in EPS:
        rows.append(rf"    \multicolumn{{5}}{{@{{}}l}}{{\emph{{{ep}}}}} \\")
        for ca, lab in CFGS:
            cells = []
            for nm, nd in (("CPU", 2), ("CPUMS", 1), ("USSI", 1), ("USSP", 1)):
                i = f"{nm}.{ea}.{ca}.c100"
                ids.append(i)
                mark = ""
                if n.rel(i) is not None and n.rel(i) > 0.10:
                    mark, wide = "$^\\dagger$", wide + 1
                cells.append(f"{f(n.v(i), nd)}{mark}")
            rows.append(f"    {lab} & " + " & ".join(cells) + r" \\")
        rows.append(r"    \addlinespace")
    rows.pop()
    rel_uss = max(n.rel(i) for i in ids if i.startswith("USS"))
    body = r"""
\begin{table}
  \caption{Server resources at $c = 100$ (median of 5 runs). CPU: mean over the loaded window, in \%% of one core
  (process tree); CPU per completed request in ms; idle (after warm-up) and peak unique set size (USS) in MiB,
  17 workers summed over 18 processes. $^\dagger$ half-width of the range of 5 runs above 10\,\%% of the value
  (%(wide)s cells; CPU samples are quantised in 4\,\%% steps); USS half-widths are at most %(rel)s\,\%%. Stream: 12 chunks per
  response (simulator); CPU per stream grows with the chunk count (Section~\ref{sec:discussion}).}
  \label{tab:resources}
  \footnotesize
  \begin{tabular}{@{}lrrrr@{}}
    \toprule
    Configuration & CPU (\%%) & CPU/req (ms) & Idle USS & Peak USS \\
    \midrule
%(rows)s
    \bottomrule
  \end{tabular}
\end{table}
""" % dict(rows="\n".join(rows), wide=wide, rel=f"{rel_uss * 100:.2f}")
    write(d, "t4_resources.tex", body, ids)


def t5(n, d):
    ids = []

    def c(i, nd, pct=False):
        ids.append(i)
        return fci(n, i, nd, pct)

    ab = [
        ("$S_{today}$: median latency at $c=1$ (ms)", c("VA.lat.p50.c1", 0), c("VB.lat.p50.c1", 0)),
        ("April thesis median at $c=1$ (ms)", f(n.v("VA.thesis.lat.p50"), 0) + r"$^\ddagger$", c("VB.thesis.lat.p50", 0)),
        ("Today / April, median latency", c("VA.drift.lat", 3), c("VB.drift.lat", 3)),
        ("$c=25$ / $c=1$, median latency", c("VA.load.lat.p50", 3), c("VB.load.lat.p50", 3)),
        ("$c=25$ / $c=1$, p95 latency", c("VA.load.lat.p95", 3), c("VB.load.lat.p95", 3)),
        ("Throughput share of $25/S_{today}$, real", c("VA.share.c25", 3), c("VB.share.c25", 3)),
        ("Throughput share, simulator scaled", c("VA.simshare.c25", 3), c("VB.simshare.c25", 3)),
        ("Real / scaled simulator, median, $c=25$", c("VA.sim4b.lat.p50", 3), c("VB.sim4b.lat.p50", 3)),
        ("Real / scaled simulator, p95, $c=25$", c("VA.sim4b.lat.p95", 3), c("VB.sim4b.lat.p95", 3)),
        ("TTFT at $c=1$, today / April (ms)", "", c("VB.ttft.p50.c1", 1) + " / " + c("VB.thesis.ttft.p50", 1)),
        ("TTFT $c=25$ / $c=1$", "", c("VB.load.ttft.p50", 3)),
        ("Chunks per response at $c=1$, today / April", "", c("VB.chunks.p50.c1", 0) + " / " + c("VB.thesis.chunks.p50", 0)),
        ("TPOT at $c=1$, today / April (ms)", "", c("VB.tpot.p50.c1", 1) + " / " + c("VB.thesis.tpot.p50", 1)),
        ("CPU at $c=25$, real (\\% of one core)", "", c("D.real.cpu.c25", 1) + r" vs sim.\ " + c("CPU.str.fastapi.c25", 1)),
    ]
    n.v("VA.thesis.lat.p50")
    ids.append("VA.thesis.lat.p50")
    rows_ab = "\n".join(f"    {a} & {b} & {cc} \\\\" for a, b, cc in ab)
    rows_c = []
    for fw, lab in (("flask", "Flask"), ("django", "Django"), ("fastapi", "FastAPI"), ("tornado", "Tornado")):
        rows_c.append(f"    {lab} & {c(f'VC.{fw}.ttft.today', 1)} & {c(f'VC.{fw}.ttft.april', 1)} & "
                      f"{c(f'VC.{fw}.ttft.ratio', 2)} & {c(f'VC.{fw}.tpot.today', 2)} & {c(f'VC.{fw}.cpums', 0)} \\\\")
    rows_c.append(r"    \addlinespace")
    rows_c.append(f"    Spread (max $-$ min) & {c('VC.spread.ttft.today', 1)} & {c('VC.spread.ttft.april', 1)} & & "
                  f"{c('VC.spread.tpot.today', 2)} & \\\\")
    pt, pa = n.v("VC.perm.today"), n.v("VC.perm.april")
    ids += ["VC.perm.today", "VC.perm.april"]
    m_, e_ = f"{pa:.1e}".split("e")
    rows_c.append(f"    Permutation $p$ & {pt:.2f} & ${m_}\\times 10^{{{int(e_)}}}$ & & & \\\\")
    body = r"""
\begin{table*}
  \caption{Validation against the real API (claude-haiku-4-5, 28 Sep 2026), FastAPI with the same harness.
  Phase A: inference; Phase B: stream; 3 runs per level (April thesis data: 5 runs). Values are pooled over
  the runs' requests; brackets: single levels today, the range of the 3 runs (no confidence interval); April
  levels, 95\,\%% bootstrap CI over the 5 runs; ratios and shares, approximate 95\,\%% bootstrap CI over runs. The simulator is scaled by $S_{today}/S_{sim}$ (%(fa)s for A, %(fb)s
  for B). $^\ddagger$ Locust 2-significant-figure bucket, no per-request data. Phase C: stream at $c=1$ for
  each framework, runs interleaved within 20 min; TTFT and TPOT in ms, CPU per request in ms.}
  \label{tab:validation}
  \footnotesize
  \begin{tabular}{@{}lll@{}}
    \toprule
    Phases A and B & A: inference & B: stream \\
    \midrule
%(ab)s
    \bottomrule
  \end{tabular}

  \vspace{6pt}
  \begin{tabular}{@{}llllll@{}}
    \toprule
    Phase C & TTFT today & TTFT April & Today / April & TPOT today & CPU/req \\
    \midrule
%(c)s
    \bottomrule
  \end{tabular}
\end{table*}
""" % dict(ab=rows_ab, c="\n".join(rows_c), fa=f(n.v("VA.factor"), 4), fb=f(n.v("VB.factor"), 4))
    ids += ["VA.factor", "VB.factor"]
    write(d, "t5_validation.tex", body, ids)


def t6(n, d):
    ids = []

    def c(i, nd, pct=False):
        ids.append(i)
        return fci(n, i, nd, pct)

    def th(i, txt):
        ids.append(i)
        n.v(i)
        return txt

    def cp(i, nd):
        return c(i, nd, True) + r"\,\%"

    rows = [
        ("Async / sync throughput, $c=100$ (inference)", th("P.th.ratio", "64"), c("RA1.inf.c100", 2),
         cp("P.d.ratio", 0), "Per-request API client and synchronised user bursts slowed the async servers"),
        ("One-worker sync throughput (req/s)", th("P.th.sync", "0.34"), c("P.v2sync", 4), cp("P.d.sync", 0),
         "Reproduced; thesis value rounded to 2 significant figures"),
        ("FastAPI throughput, $c=100$ (req/s)", th("P.th.fastapiX", "21.74"), c("X.inf.fastapi.c100", 2),
         cp("P.d.fastapiX", 0), "Per-request client, bursts; Locust request rate over ramp and idle time"),
        ("Async latency, $c=100$ (ms)", th("P.th.asynclat", "4,500"), c("P.asynclat", 0), cp("P.d.asynclat", 0),
         "Per-request client, bursts"),
        ("FastAPI / Tornado TTFT, $c=100$ (ms)", th("P.th.ttft.fastapi", "1,787") + " / " + th("P.th.ttft.tornado", "2,003"),
         c("TTFT.str.fastapi.c100", 1) + " / " + c("TTFT.str.tornado.c100", 1),
         cp("P.d.ttft.fastapi", 0) + " / " + cp("P.d.ttft.tornado", 0), "Per-request client, bursts"),
        ("Flask / Django TTFT, $c=100$ (ms)", th("P.th.ttft.flask", "28,163") + " / " + th("P.th.ttft.django", "28,113"),
         c("TTFT.str.flask.c100", 0) + " / " + c("TTFT.str.django.c100", 0),
         cp("P.d.ttft.flask", 1) + " / " + cp("P.d.ttft.django", 1),
         "Both cut off by the 60 s window; steady state is " + c("P.ttft.growth", 1) + r"$\times$ longer"),
        ("Stage 2 (50 ms sleep), $c=100$ (ms)", th("P.th.st2.fastapi", "643.9") + " / " + th("P.th.st2.tornado", "468.6"),
         c("ST2.fastapi.c100", 2) + " / " + c("ST2.tornado.c100", 2),
         cp("P.d.st2.fastapi", 0) + " / " + cp("P.d.st2.tornado", 0),
         "Sleep resumed late on an event loop busy with client creation during bursts"),
        ("Async / sync peak RSS, inference", th("P.th.mem.inf", "2.9"), c("MRSS.inf.c100", 3), cp("P.d.mem.inf", 0),
         "Memory carried over between runs (no restart); live per-request clients"),
        ("Async / sync peak RSS, stream", th("P.th.mem.str", "4.5"), c("MRSS.str.c100", 3), cp("P.d.mem.str", 0),
         "Same"),
        ("FastAPI peak RSS, stream, $c=100$ (MiB)", th("P.th.fastapiRSS", "332.2"), c("RSSP.str.fastapi.c100", 1),
         cp("P.d.fastapiRSS", 0), "Same"),
        ("Real TTFT spread over frameworks, $c=1$ (ms)", c("VC.spread.ttft.april", 1), c("VC.spread.ttft.today", 1),
         cp("P.d.spread", 0), "API drift between per-framework blocks (Phase C interleaved)"),
        ("Real inference service time, $c=1$ (ms)", th("VA.thesis.lat.p50", "2,800") + r"$^\ddagger$",
         c("VA.lat.p50.c1", 0), cp("P.d.S", 0), "API became slower (not a harness effect)"),
        ("Real chunks per streamed response", c("VB.thesis.chunks.p50", 0), c("VB.chunks.p50.c1", 0),
         c("VB.drift.chunks", 2) + r"$\times$", "API streams finer chunks (not a harness effect)"),
    ]
    body = r"""
\begin{table*}
  \caption{Thesis headline numbers versus the corrected harness (v2). Thesis values as printed in the thesis;
  v2 values with the range of 5 runs (a 93.75\,\%% confidence interval for the median), or a 95\,\%% bootstrap CI
  for ratios; the difference is v2 / thesis $- 1$, without an interval, rounded to the precision of the thesis value. The last three rows compare the real API in April and on
  28 Sep 2026 (April spread over 5 runs per framework in separate blocks; today 3 interleaved runs).
  $^\ddagger$ Locust 2-significant-figure bucket.}
  \label{tab:thesis}
  \footnotesize
  \begin{tabular}{@{}p{0.19\textwidth}p{0.09\textwidth}p{0.2\textwidth}p{0.17\textwidth}p{0.23\textwidth}@{}}
    \toprule
    Quantity & Thesis & v2 [interval] & Difference & Cause \\
    \midrule
%(rows)s
    \bottomrule
  \end{tabular}
\end{table*}
""" % dict(rows="\n".join(f"    {a} & {b} & {cc} & {dd} & {e} \\\\" for a, b, cc, dd, e in rows))
    write(d, "t6_thesis_vs_v2.tex", body, ids)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--paper-dir", default=os.path.expanduser("~/paper_context/paper"))
    a = ap.parse_args()
    d = os.path.join(a.paper_dir, "tables")
    os.makedirs(d, exist_ok=True)
    n = N()
    for fn in (t1, t2, t3, t4, t5, t6):
        fn(n, d)
    print(f"Saved {len(os.listdir(d))} files in {d}; {len(set(n.used))} numbers.csv ids used")


if __name__ == "__main__":
    main()
