"""
Write NUMBERS.md, the single source of truth for writing the paper, from the outputs of
paper_stats.py (read-only on data; no computation of new statistics here).

Inputs:  analysis/out/paper/numbers.csv, numbers_meta.csv
Output:  <paper dir>/NUMBERS.md (default ~/paper_context/paper)

One row per number printed in the paper text or tables, grouped by paper section. Rows that are
only plotted (figure data) or only feed a range row are listed by id pattern and count, and are in
numbers.csv. The claim-impact notes at the top are fixed text with the values filled in from
numbers.csv, so they stay in step with the statistics.

Usage: venv/bin/python analysis/scripts/paper_numbers_md.py [--paper-dir DIR]
"""

import argparse
import csv
import os
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
IN = os.path.join(ROOT, "analysis", "out", "paper")

SECTIONS = [
    ("4 Methodology", "4 Methodology (setup, integrity, simulator constants)"),
    ("5.1 Capacity", "5.1 Results: capacity"),
    ("5.2 Latency", "5.2 Results: latency"),
    ("5.3 Resources", "5.3 Results: resources"),
    ("5.4 Same-class", "5.4 Results: same-class equivalence"),
    ("5.5 Multi-worker", "5.5 Results: multi-worker (17 Gunicorn sync workers)"),
    ("6 Validation", "6 Validation against the real API"),
    ("7 Pitfalls", "7 Measurement pitfalls (thesis vs v2)"),
    ("8 Discussion", "8 Discussion (streaming CPU, projection)"),
    ("9 Threats", "9 Threats to validity"),
    ("T2", "Table T2 cells: throughput and share of the ceiling"),
    ("T3", "Table T3 cells: latency (steady state; R = N/X where censored)"),
    ("T4", "Table T4 cells: resources at c = 100"),
]

HEADLINE = [
    ("RA1.inf.c100", "Async (FastAPI, Tornado) / one-worker sync (Flask, Django) throughput, inference, c = 100 "
                     "(thesis: 64)"),
    ("RA17.inf.c100", "Async / 17-worker sync throughput, inference, c = 100 (theory 100 / 17 = 5.882)"),
    ("X.inf.fastapi.c100", "FastAPI throughput, inference, c = 100 (c/S = 34.75 req/s)"),
    ("X.inf.flask.c100", "Flask (one sync worker) throughput, inference, c = 100 (1/S = 0.3475 req/s)"),
    ("N.SSU1.c10", "Full-window mean understates the one-worker steady-state latency, c = 10 (all endpoints)"),
    ("N.SC.USSP.django_flask", "Django peak USS above Flask (all endpoints and c); throughput differs by at most "
                               "0.08 % within a class"),
    ("MRSS.inf.c100", "Async / one-worker sync peak RSS, inference, c = 100 (thesis: 2.9)"),
    ("ST2.fastapi.c100", "Pipeline Stage 2 (50 ms sleep) p50, FastAPI, c = 100 (thesis: 643.9 ms)"),
    ("VA.load.lat.p50", "Real API (FastAPI inference): median latency c = 25 / c = 1"),
    ("D.real.cpu.c25", "Real API FastAPI stream CPU at c = 25 (about 92 chunks; simulator with 12 chunks: 20.8 %)"),
]


def read(path):
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def f(x, nd):
    if x in (None, ""):
        return "n/a"
    try:
        v = float(x)
    except ValueError:
        return x
    return f"{v:,.{nd}f}"


def unit_txt(u):
    return {"fraction": "(fraction of the ceiling)", "ratio": "(ratio)", "x": "x", "p": "(p-value)"}.get(u, u)


def val(r, nd):
    v = r["value"]
    s = f"{f(v, nd)} {unit_txt(r['unit'])}"
    if r["ci_low"] != "":
        s += f" [{f(r['ci_low'], nd)}, {f(r['ci_high'], nd)}]"
    else:
        s += " (no CI)"
    if r["min"] != "":
        s += f"; runs {f(r['min'], nd)} to {f(r['max'], nd)}"
    s += f"; n {r['n_runs']}"
    return s


def esc(s):
    return s.replace("|", "/")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--paper-dir", default=os.path.expanduser("~/paper_context/paper"))
    a = ap.parse_args()
    nums = {r["id"]: r for r in read(os.path.join(IN, "numbers.csv"))}
    meta = {r["id"]: r for r in read(os.path.join(IN, "numbers_meta.csv"))}
    order = list(nums)
    sha = subprocess.run(["git", "-C", ROOT, "rev-parse", "--short", "HEAD"], capture_output=True, text=True).stdout.strip()

    def V(i, nd=None):
        return val(nums[i], int(meta[i]["decimals"]) if nd is None else nd)

    def printed(i):
        u = meta[i]["used_in"]
        return not (u in ("numbers.csv only", "F3", "F6", "F4") or "(range)" in u)

    L = []
    L.append("# NUMBERS: every number planned for the paper, with 95 % confidence intervals\n")
    L.append(f"Generated by `venv/bin/python analysis/scripts/paper_numbers_md.py` from analysis/out/paper/numbers.csv "
             f"and numbers_meta.csv, which `venv/bin/python analysis/scripts/paper_stats.py` computes from the frozen data "
             f"(tag v2-freeze; repository HEAD {sha}; the scripts are committed with tag v2-analysis). "
             f"Paths are relative to /home/sanidhya/experiment. numbers.csv holds {len(nums):,} numbers with the full "
             f"method text per row; this file lists the {sum(1 for i in order if printed(i)):,} that are printed in the "
             f"paper text or tables.\n")
    L.append("How to read a row: value = the estimator of RESULTS_FINAL.md (median of the 5 per-run values, a pooled "
             "statistic, or a ratio as defined there) with its unit; [lo, hi] = 95 % CI; runs a to b = range of the "
             "per-run values (for multi-group statistics: over all combinations of one run per group); n = runs per "
             "group. CI methods: one group of runs: t-interval of the mean of the per-run values (n = 5: df 4, "
             "t = 2.7764; real API n = 3: df 2, t = 4.3027); ratios and any statistic that combines groups of runs: "
             "percentile bootstrap over runs (10,000 resamples, runs resampled within each group, seed 20260929 + "
             "crc32(id)). Because the reported value is a median or a pooled statistic while the t-interval is for the "
             "mean of the per-run values, a value can sit near an edge of its interval; rows where it lies more than "
             "0.5 % outside are flagged. Units: MiB for memory (MB in the paper means MiB), % of one core for CPU, "
             "ms per chunk for TPOT.\n")

    # ---------------- headline
    L.append("## Headline numbers\n")
    L.append("| # | id | statement | value [95 % CI] | used in |")
    L.append("|--:|---|---|---|---|")
    for k, (i, s) in enumerate(HEADLINE, 1):
        L.append(f"| H{k} | {i} | {s} | {V(i)} | {meta[i]['used_in']} |")
    L.append("")

    # ---------------- claim impact
    L.append("## Numbers whose CI is wide enough to change a claim\n")
    L.append("Assessment written for this file; values filled in from numbers.csv. The automatic flags of every row "
             "follow in the next table.\n")
    def ci(i, nd=None, pct=False):
        nd = int(meta[i]["decimals"]) if nd is None else nd
        lo, hi = float(nums[i]["ci_low"]), float(nums[i]["ci_high"])
        if pct:
            return f"{(lo - 1) * 100:+.0f} to {(hi - 1) * 100:+.0f} %"
        return f"[{lo:,.{nd}f}, {hi:,.{nd}f}]"

    def hi_(i):
        return float(nums[i]["ci_high"])

    def lo_(i):
        return float(nums[i]["ci_low"])

    def resolved(i):
        return int(nums[i]["description"].split("CI excludes 0 in ")[1].split(" ")[0])

    def unresolved(i):
        fl = meta[i]["flag"]
        return fl.split(": ", 1)[1] if ": " in fl else "none"

    sc_cpu = resolved("N.SC.CPU.django_flask")
    uss_all = all(resolved(f"N.SC.{m}.{p}") == 18 for m in ("USSI", "USSP")
                  for p in ("django_flask", "fastapi_tornado", "django17w_flask17w"))
    impact = [
        ("P.d.S", "Real inference service time today vs April. The paper framing says 'about 25 % slower'; the "
                  f"95 % CI is {ci('P.d.S', 1)} % (3 runs today whose medians differ by 12 % because of two output "
                  f"modes; today / April = {V('VA.drift.lat', 3)}). Write '26 % slower (95 % CI 16 to 34 %)' or "
                  "'about 16 to 34 % slower'. The direction (slower) is not in doubt."),
        ("VA.lat.p50.c1", "S_today itself (t-interval over 3 run medians) is uncertain by about +/- 16 %; every "
                          "quantity scaled by S_today (the simulator-vs-real comparisons, the throughput shares) "
                          "inherits this."),
        ("VA.load.lat.p50", "Real load effect at c = 25 (inference). The point value says no penalty, but the CI "
                            f"admits {ci('VA.load.lat.p50', pct=True)}; the within-mode ratios (0.969 to 1.009, "
                            "RESULTS_FINAL 5.4) are the stronger evidence. Word the claim as 'no load effect larger "
                            "than about 10 % at c = 25 (3 runs per level)'."),
        ("VB.load.lat.p50", f"Same for streaming: the CI admits {ci('VB.load.lat.p50', pct=True)}. The TTFT ratio "
                            f"({V('VB.load.ttft.p50', 3)}) excludes a TTFT penalty."),
        ("VA.share.c25", f"Real throughput share of 25 / S_today: the bootstrap resamples S_today too, so the CI is "
                         f"{ci('VA.share.c25')}. 'Throughput follows c / S on the real API' holds to within about "
                         "10 % with 3 runs per level, not to 0.1 %."),
        ("VB.share.c25", f"Same for streaming: {ci('VB.share.c25')}."),
        ("VC.spread.ttft.today", "Phase C framework spread of real c = 1 TTFT today: the CI upper bound "
                                 f"({hi_('VC.spread.ttft.today'):.0f} ms) means a framework effect of that size cannot "
                                 "be excluded with 3 runs per framework. The April spread "
                                 f"({V('VC.spread.ttft.april', 1)}) has a lower bound of {lo_('VC.spread.ttft.april'):.0f} ms, "
                                 "above today's upper bound, so 'the April spread was mostly API drift' holds; 'no "
                                 "framework effect' does not (say 'below about 55 ms')."),
        ("N.SC.CPU.django_flask", f"Flask vs Django CPU: the CI excludes 0 in only {sc_cpu} of 18 cells (unresolved: "
                                  f"{unresolved('N.SC.CPU.django_flask')}). The framing 'within a class, frameworks "
                                  "differ only in CPU and memory' holds for FastAPI vs Tornado (CPU resolved in "
                                  f"{resolved('N.SC.CPU.fastapi_tornado')} of 18 cells; idle and peak USS resolved in "
                                  f"{'all cells of all three pairs' if uss_all else 'some cells only, see flags'}), but "
                                  "for Flask vs Django only memory is resolved (Django peak USS "
                                  f"{nums['N.SC.USSP.django_flask']['value']} %); do not claim a Flask vs Django CPU "
                                  "difference."),
        ("N.SC.CPU.django17w_flask17w", f"17-worker pair CPU: resolved in {resolved('N.SC.CPU.django17w_flask17w')} "
                                        f"of 18 cells; unresolved: {unresolved('N.SC.CPU.django17w_flask17w')}. Quote "
                                        "only the resolved cells (inference c >= 5, pipeline c >= 25)."),
        ("SC.CPU.fastapi_tornado.inf.c1", "FastAPI vs Tornado CPU at inference c = 1 (quoted as +178 %): resolved "
                                          f"but imprecise, CI {ci('SC.CPU.fastapi_tornado.inf.c1', 0)} %; it is a "
                                          "ratio of 0.42 and 0.15 % of one core. Quote the c = 100 value "
                                          f"({V('SC.CPU.fastapi_tornado.inf.c100', 1)}) as the robust one."),
        ("D.m2.fastapi.c50", "Streaming CPU projection at c = 50: Method 2 (anchored on the real c = 25 "
                             f"measurement) gives {V('D.m2.fastapi.c50', 0)}, below one core with its CI, while Method 1 "
                             f"gives {V('D.m1.fastapi.c50', 0)}. The RESULTS_FINAL statement 'at c = 50, FastAPI is at "
                             "or above one core' is not supported by Method 2; state only the c = 100 projection, where "
                             "both methods and their CIs exceed 100 % (INFERRED; the CIs cover input spread, not model "
                             "error)."),
        ("VA.sim4b.lat.p95", "Simulator vs real p95 after scaling: the CI is wide and one-sided (up to about 2 x); "
                             "only the median agreement is a claim, the tails are a threat (Section 9)."),
    ]
    L.append("| id | value [95 % CI] | impact on the claim |")
    L.append("|---|---|---|")
    for i, txt in impact:
        L.append(f"| {i} | {V(i)} | {esc(txt)} |")
    L.append("")
    L.append("Projections at c = 50 and 100 (INFERRED; CIs propagate the run-to-run spread of the inputs only, not the "
             "model error of the methods; Method 1 overpredicts the measured c = 25 CPU by "
             f"{V('D.m1.check.c25', 2)}):\n")
    L.append("| id | projection | value [95 % CI] | flag |")
    L.append("|---|---|---|---|")
    for i in [x for x in order if x.startswith(("D.m1.", "D.m2."))]:
        fl = meta[i]["flag"] or ("CI excludes 100 %" if nums[i]["unit"].startswith("%") else "")
        L.append(f"| {i} | {esc(nums[i]['description'])} | {V(i)} | {esc(fl)} |")
    L.append("")

    # ---------------- automatic flags
    L.append("## All automatically flagged rows\n")
    bulk = [i for i in order if meta[i]["flag"] and i.split(".")[0] in ("CPU", "CPUMS") and not printed(i)]
    bulk_p = [i for i in order if meta[i]["flag"] and i.split(".")[0] in ("CPU", "CPUMS") and printed(i)]
    cens = [i for i in order if meta[i]["flag"].startswith("censored")]
    cpu_max = max(float(nums["CPU." + i.split(".", 1)[1]]["value"]) for i in bulk + bulk_p)
    L.append(f"- {len(bulk) + len(bulk_p)} CPU cells (CPU.*, CPUMS.*) have a CI half-width above 10 % of the value; all "
             f"are cells with mean CPU of at most {cpu_max:.2f} % of one core, where the 250 ms samples are quantised in "
             "4 % steps. "
             f"Printed in T4: {', '.join(bulk_p) if bulk_p else 'none'}. They change no claim (the claims about "
             "one-worker CPU use ranges such as 0.13 to 0.50 % of one core).")
    L.append(f"- {len(cens)} TTFT cells are censored by the 60 s window (one worker, c >= 25): {', '.join(cens)}; use "
             "the derived steady-state TTFT (TTFTD.*) for claims.")
    L.append("")
    L.append("| id | value [95 % CI] | flag | used in |")
    L.append("|---|---|---|---|")
    for i in order:
        if meta[i]["flag"] and i not in bulk + bulk_p + cens:
            L.append(f"| {i} | {V(i)} | {esc(meta[i]['flag'])} | {meta[i]['used_in']} |")
    L.append("")

    # ---------------- corrections
    L.append("## Corrections to RESULTS_FINAL.md found while recomputing\n")
    pa = nums["VC.perm.april"]
    L.append(f"- Phase C, April permutation test: RESULTS_FINAL 5.6 says 'no permutation reached the observed value; "
             f"p = 5.0e-6 = 1 / 200,001'. The recomputation (final_real.perm_test, 200,000 permutations, seed 1; the "
             f"same value is in analysis/out/final_phase_c_test.csv) gives p = {float(pa['value']):.2e}, i.e. 8 "
             f"permutations reached it. The conclusion (p < 0.0001) is unchanged; quote p = {float(pa['value']):.1e}.")
    L.append("- All other recomputed values equal the RESULTS_FINAL outputs (298 automatic checks against final_mw.csv, "
             "final_mw_ratio.csv, final_steady_state.csv, final_phase_c.csv, final_stream_cpu.csv and "
             "results_v2/validation_real_v2*.csv; log ~/paper_context/logs/paper_stats.log).")
    L.append("")

    # ---------------- sections
    for key, title in SECTIONS:
        ids = [i for i in order if meta[i]["section"] == key and printed(i)]
        hidden = [i for i in order if meta[i]["section"] == key and not printed(i)]
        L.append(f"## {title}\n")
        if hidden:
            pats = sorted({i.split(".")[0] for i in hidden})
            L.append(f"Not printed (figure data or inputs of the range rows; in numbers.csv): {len(hidden)} numbers, "
                     f"id prefixes {', '.join(p + '.*' for p in pats)}.\n")
        if not ids:
            continue
        L.append("| id | description | value [95 % CI]; runs; n | used in | source |")
        L.append("|---|---|---|---|---|")
        for i in ids:
            r = nums[i]
            L.append(f"| {i} | {esc(r['description'])} | {V(i)} | {meta[i]['used_in']} | {esc(r['source_files'])} |")
        L.append("")
    other = [i for i in order if meta[i]["section"] not in dict(SECTIONS) and printed(i)]
    if other:
        L.append("## Other printed numbers\n")
        L.append("| id | description | value [95 % CI]; runs; n | used in | source |")
        L.append("|---|---|---|---|---|")
        for i in other:
            L.append(f"| {i} | {esc(nums[i]['description'])} | {V(i)} | {meta[i]['used_in']} | "
                     f"{esc(nums[i]['source_files'])} |")
    os.makedirs(a.paper_dir, exist_ok=True)
    out = os.path.join(a.paper_dir, "NUMBERS.md")
    text = "\n".join(L) + "\n"
    assert "\u2014" not in text and "\u2013" not in text, "dash character found"
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"Saved {out}: {sum(1 for i in order if printed(i))} printed numbers of {len(nums)}")


if __name__ == "__main__":
    main()
