"""
Simulated Anthropic Messages API for the benchmark (v2).

Serves POST /v1/messages in the wire format of the Anthropic API as consumed by
the installed anthropic SDK 0.88.0, so the frameworks use the SAME SDK client and
call path in real and simulated mode (only base_url and the API key differ):

  non-streaming: one JSON Message object
  streaming:     SSE events message_start, content_block_start, ping,
                 content_block_delta (text_delta) x N, content_block_stop,
                 message_delta, message_stop

Timing is deterministic (no jitter, by design) and comes only from
simulated_endpoint/calibration_v2.json (generated by scripts/calibrate_from_data.py):

  non-streaming inference   sleep inference_delay_s, then respond
  non-streaming pipeline    sleep pipeline_delay_s (user message starts with
                            pipeline_prompt_prefix), then respond
  streaming                 message_start, content_block_start, ping at t = 0;
                            text chunk i (0-based) at the absolute deadline
                            stream_first_chunk_delay_s + i * stream_chunk_interval_s;
                            content_block_stop, message_delta, message_stop
                            immediately after the last chunk

A missing calibration file or key is a fatal error (no silent defaults).

Optional: SIM_REQUEST_LOG=<path> appends every request body as one JSON line
(used by the contract tests to prove the request parameters).

Runs on port 9000. Tornado is a utility server here, not a benchmarked framework.

Usage:
  python simulated_endpoint/simulator.py
"""

import asyncio
import hashlib
import itertools
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import tornado.httpserver
import tornado.ioloop
import tornado.web

CALIBRATION_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "calibration_v2.json")

REQUIRED_KEYS = (
    "model",
    "inference_delay_s",
    "pipeline_delay_s",
    "pipeline_prompt_prefix",
    "stream_first_chunk_delay_s",
    "stream_chunk_interval_s",
    "stream_chunk_count",
    "inference_text_bytes",
    "pipeline_text_bytes",
    "inference_input_tokens",
    "pipeline_input_tokens",
    "output_tokens",
    "stop_reason",
    "service_time_s",
)

SIMULATOR_PORT = 9000

# ASCII filler; repeated and cut to the calibrated byte length.
_FILLER_SENTENCE = (
    "Generative AI refers to machine learning systems that produce new text, images or code "
    "from a prompt, and web applications integrate it by sending user input to an inference "
    "API and returning the generated output to the client. "
)


def load_calibration(path=CALIBRATION_FILE):
    """Load calibration_v2.json and fail loudly on a missing file or key."""
    if not os.path.exists(path):
        raise SystemExit(f"FATAL: calibration file not found: {path}. Run scripts/calibrate_from_data.py")
    with open(path, "rb") as f:
        raw = f.read()
    doc = json.loads(raw)
    values = doc.get("values")
    if not isinstance(values, dict):
        raise SystemExit(f"FATAL: {path} has no 'values' object")
    missing = [k for k in REQUIRED_KEYS if k not in values]
    if missing:
        raise SystemExit(f"FATAL: {path} is missing keys: {missing}")
    for ep in ("inference", "stream", "pipeline"):
        if ep not in values["service_time_s"]:
            raise SystemExit(f"FATAL: {path} service_time_s is missing '{ep}'")
    return values, hashlib.sha256(raw).hexdigest()


def make_text(n_bytes):
    reps = n_bytes // len(_FILLER_SENTENCE) + 1
    return (_FILLER_SENTENCE * reps)[:n_bytes]


def split_chunks(text, n):
    """Split text into n contiguous chunks of near-equal length."""
    bounds = [round(i * len(text) / n) for i in range(n + 1)]
    return [text[bounds[i]:bounds[i + 1]] for i in range(n)]


CAL, CAL_SHA256 = load_calibration()
INFERENCE_TEXT = make_text(CAL["inference_text_bytes"])
PIPELINE_TEXT = make_text(CAL["pipeline_text_bytes"])
STREAM_CHUNKS = split_chunks(INFERENCE_TEXT, CAL["stream_chunk_count"])
_ids = itertools.count(1)
_REQUEST_LOG = os.environ.get("SIM_REQUEST_LOG")


def _user_text(body):
    """Text of the last user message (string content or list of text blocks)."""
    messages = body.get("messages") or []
    if not messages:
        return ""
    content = messages[-1].get("content", "")
    if isinstance(content, list):
        return "".join(b.get("text", "") for b in content if isinstance(b, dict))
    return content


def _usage(is_pipeline):
    return {
        "input_tokens": CAL["pipeline_input_tokens"] if is_pipeline else CAL["inference_input_tokens"],
        "output_tokens": CAL["output_tokens"],
        "cache_creation_input_tokens": 0,
        "cache_read_input_tokens": 0,
        "service_tier": "standard",
    }


def _message(model, content, stop_reason, usage):
    return {
        "id": f"msg_sim_{next(_ids):08d}",
        "type": "message",
        "role": "assistant",
        "model": model,
        "content": content,
        "stop_reason": stop_reason,
        "stop_sequence": None,
        "usage": usage,
    }


class MessagesHandler(tornado.web.RequestHandler):
    """POST /v1/messages, streaming and non-streaming."""

    async def post(self):
        body = json.loads(self.request.body or b"{}")
        if _REQUEST_LOG:
            with open(_REQUEST_LOG, "a", encoding="utf-8") as f:
                f.write(json.dumps(body) + "\n")

        model = body.get("model", CAL["model"])
        is_pipeline = _user_text(body).startswith(CAL["pipeline_prompt_prefix"])

        if body.get("stream"):
            await self._stream(model, is_pipeline)
        else:
            await self._complete(model, is_pipeline)

    async def _complete(self, model, is_pipeline):
        await asyncio.sleep(CAL["pipeline_delay_s"] if is_pipeline else CAL["inference_delay_s"])
        text = PIPELINE_TEXT if is_pipeline else INFERENCE_TEXT
        msg = _message(model, [{"type": "text", "text": text}], CAL["stop_reason"], _usage(is_pipeline))
        self.set_header("Content-Type", "application/json")
        self.write(json.dumps(msg))

    def _event(self, name, data):
        self.write(f"event: {name}\ndata: {json.dumps(data)}\n\n")

    async def _stream(self, model, is_pipeline):
        chunks = split_chunks(PIPELINE_TEXT, CAL["stream_chunk_count"]) if is_pipeline else STREAM_CHUNKS
        usage = _usage(is_pipeline)
        start_usage = dict(usage, output_tokens=1)

        self.set_header("Content-Type", "text/event-stream")
        self.set_header("Cache-Control", "no-cache")
        self._event("message_start", {"type": "message_start",
                                      "message": _message(model, [], None, start_usage)})
        self._event("content_block_start", {"type": "content_block_start", "index": 0,
                                            "content_block": {"type": "text", "text": ""}})
        self._event("ping", {"type": "ping"})
        self.flush()

        # Absolute deadlines from the request start, so sleep overshoot does not accumulate
        loop = asyncio.get_running_loop()
        t0 = loop.time()
        for i, chunk in enumerate(chunks):
            deadline = t0 + CAL["stream_first_chunk_delay_s"] + i * CAL["stream_chunk_interval_s"]
            await asyncio.sleep(max(0.0, deadline - loop.time()))
            self._event("content_block_delta", {"type": "content_block_delta", "index": 0,
                                                "delta": {"type": "text_delta", "text": chunk}})
            self.flush()

        self._event("content_block_stop", {"type": "content_block_stop", "index": 0})
        self._event("message_delta", {"type": "message_delta",
                                      "delta": {"stop_reason": CAL["stop_reason"], "stop_sequence": None},
                                      "usage": {"output_tokens": CAL["output_tokens"]}})
        self._event("message_stop", {"type": "message_stop"})
        self.flush()


class HealthHandler(tornado.web.RequestHandler):
    """Health check reporting the calibration in use and its hash."""

    def get(self):
        self.set_header("Content-Type", "application/json")
        self.write(json.dumps({
            "status": "ok",
            "service": "simulated_messages_api",
            "calibration_sha256": CAL_SHA256,
            "calibration": CAL,
        }))


def make_app():
    return tornado.web.Application([
        (r"/v1/messages", MessagesHandler),
        (r"/health", HealthHandler),
    ])


if __name__ == "__main__":
    server = tornado.httpserver.HTTPServer(make_app())
    server.listen(SIMULATOR_PORT, address="127.0.0.1")
    print(f"Simulated Messages API listening on http://127.0.0.1:{SIMULATOR_PORT}")
    print(f"Calibration sha256: {CAL_SHA256}")
    tornado.ioloop.IOLoop.current().start()
